package com.phone.contacts.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/** A contact (or a preset emergency service number like "Ambulance") the user has marked as an
 * emergency contact. [sourceKey] is a stable identity used to detect "already added" when
 * re-opening the picker: a real contact's own id, or a preset's fixed id (e.g. "preset_ambulance")
 * — distinct from Room's own autogenerated [id], which the UI never needs to know about.
 * [photoUri] is null for presets, which aren't real contacts and have no photo. */
@Entity(tableName = "emergency_contacts")
data class EmergencyContactEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val sourceKey: String,
    val name: String,
    val number: String,
    val photoUri: String? = null,
    val addedAt: Long = System.currentTimeMillis()
)
